import type { Metadata } from 'next'

// These styles apply to every route in the application

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import '@/app/ui/global.css';
import { inter } from '@/app/ui/fonts';
import styles from '@/app/ui/home.module.css';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
